spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/employees
    username: admin
    password: admin
    driverClassName: com.mysql.jdbc.Driver
