spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/employee
    username: admin
    password: admin
    driverClassName: com.mysql.jdbc.Driver
